#ifndef KICAD_PCB_LAYER_H
#define KICAD_PCB_LAYER_H

#define PCB_LAYER_EDGE_CUT_STR "Edge.Cuts"
#define PCB_LAYER_EDGE_CUT_ID 44
#define PCB_LAYER_FRONT_CRTYD_STR "F.CrtYd"
#define PCB_LAYER_FRONT_CRTYD_ID 45
#define PCB_LAYER_BOTTOM_CRTYD_STR "B.CrtYd"
#define PCB_LAYER_BOTTOM_CRTYD_ID 46

#endif