#ifndef KICAD_PCB_LAYER_H
#define KICAD_PCB_LAYER_H


#define PCB_LAYER_BOTTOM_ADHES_STR "B.Adhes"
#define PCB_LAYER_BOTTOM_ADHES_ID 32
#define PCB_LAYER_FRONT_ADHES_STR "F.Adhes"
#define PCB_LAYER_FRONT_ADHES_ID 33
#define PCB_LAYER_BOTTOM_PASTE_STR "B.Paste"
#define PCB_LAYER_BOTTOM_PASTE_ID 34
#define PCB_LAYER_FRONT_PASTE_STR "F.Paste"
#define PCB_LAYER_FRONT_PASTE_ID 35
#define PCB_LAYER_BOTTOM_SILKS_STR "B.SilkS"
#define PCB_LAYER_BOTTOM_SILKS_ID 36
#define PCB_LAYER_FRONT_SILKS_STR "F.SilkS"
#define PCB_LAYER_FRONT_SILKS_ID 37
#define PCB_LAYER_BOTTOM_MASK_STR "B.Mask"
#define PCB_LAYER_BOTTOM_MASK_ID 38
#define PCB_LAYER_FRONT_MASK_STR "F.Mask"
#define PCB_LAYER_FRONT_MASK_ID 39
#define PCB_LAYER_EDGE_CUT_STR "Edge.Cuts"
#define PCB_LAYER_EDGE_CUT_ID 44
#define PCB_LAYER_BOTTOM_CRTYD_STR "B.CrtYd"
#define PCB_LAYER_BOTTOM_CRTYD_ID 46
#define PCB_LAYER_FRONT_CRTYD_STR "F.CrtYd"
#define PCB_LAYER_FRONT_CRTYD_ID 47
#define PCB_LAYER_BOTTOM_FAB_STR "B.Fab"
#define PCB_LAYER_BOTTOM_FAB_ID 48
#define PCB_LAYER_FRONT_FAB_STR "F.Fab"
#define PCB_LAYER_BOTTOM_FAB_ID 49


#endif